//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staff_Schedulling_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        public string Id { get; set; }
        public string StaffId { get; set; }
        public int Day { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public System.DateTime Date { get; set; }
        public string WardId { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Ward Ward { get; set; }
    }
}
